# Internal Winenv implementation. Dot-sourced by win.ps1; not a public API.

function Get-MiseCandidates {
    param(
        [string]$Query,
        [switch]$Installed
    )
    if (-not (Test-Command "mise")) { return @() }

    if ($Installed) {
        $result = Invoke-CapturedCommand "mise" @("ls", "--json")
        if ($result.ExitCode -ne 0) { return @() }
        $inventory = (($result.Lines -join "`n") | ConvertFrom-Json)
        return @($inventory.psobject.Properties | ForEach-Object {
            $id = [string]$_.Name
            $active = @($_.Value | Where-Object { $_.active } | Select-Object -First 1)
            if (($active.Count -gt 0) -and ([string]::IsNullOrWhiteSpace($Query) -or $id.IndexOf($Query, [StringComparison]::OrdinalIgnoreCase) -ge 0)) {
                $requestedVersion = if (@($active[0].psobject.Properties.Name) -contains "requested_version") { [string]$active[0].requested_version } else { "" }
                New-PackageCandidate -ManagerName "mise" -Id $id -Name $id -Version $active[0].version -Source "mise" -RequestedVersion $requestedVersion
            }
        })
    }

    $result = Invoke-CapturedCommand "mise" @("registry", "--json")
    if ($result.ExitCode -ne 0) { return @() }
    $registry = @((($result.Lines -join "`n") | ConvertFrom-Json))
    return @($registry | Where-Object {
        $searchable = @([string]$_.short, [string]$_.description, (@($_.aliases) -join " "), (@($_.backends) -join " ")) -join " "
        $searchable.IndexOf($Query, [StringComparison]::OrdinalIgnoreCase) -ge 0
    } | Select-Object -First 50 | ForEach-Object {
        New-PackageCandidate -ManagerName "mise" -Id $_.short -Name $_.short -Source (@($_.backends)[0]) -Description $_.description
    })
}

function Ensure-Mise {
    $probe = Get-ManagerProbe "mise"
    if ($probe.Status -eq "available") {
        $ResolvedManagerCommands["mise"] = $probe.Path
        return
    }
    if ($probe.Status -eq "broken") {
        throw "mise exists at $($probe.Path), but 'mise --version' failed. Fix or remove that installation before continuing."
    }

    Ensure-Scoop
    Write-Step "Installing mise with Scoop"
    Invoke-Native (Get-ResolvedManagerCommand "scoop") @("install", "mise")
    if ($DryRun) { return }

    Refresh-ProcessPath
    $probe = Get-ManagerProbe "mise"
    if ($probe.Status -ne "available") {
        throw "mise was installed but is not visible in this process. Open a new PowerShell window and run the command again."
    }
    $ResolvedManagerCommands["mise"] = $probe.Path
}

function Install-MisePackage {
    param(
        $Package,
        [switch]$ProfileManaged
    )
    $version = if ($Package.version) { [string]$Package.version } else { "latest" }
    if ($ProfileManaged) {
        Invoke-Native (Get-ResolvedManagerCommand "mise") @("install", "$($Package.id)@$version")
    } else {
        Invoke-Native (Get-ResolvedManagerCommand "mise") @("use", "--global", "$($Package.id)@$version")
    }
}

function Test-MiseVersionSatisfied {
    param(
        [string]$Requested,
        $Candidate
    )
    if ([string]::IsNullOrWhiteSpace($Requested) -or $Requested -eq "latest") { return $true }
    if (-not [string]::IsNullOrWhiteSpace([string]$Candidate.RequestedVersion) -and
        ([string]$Candidate.RequestedVersion).Equals($Requested, [StringComparison]::OrdinalIgnoreCase)) {
        return $true
    }
    $actual = [string]$Candidate.Version
    return $actual.Equals($Requested, [StringComparison]::OrdinalIgnoreCase) -or
        $actual.StartsWith("$Requested.", [StringComparison]::OrdinalIgnoreCase) -or
        $actual.StartsWith("$Requested-", [StringComparison]::OrdinalIgnoreCase)
}

function Get-WinenvMiseConfigPath {
    $configRoot = if (-not [string]::IsNullOrWhiteSpace($env:MISE_CONFIG_DIR)) {
        $env:MISE_CONFIG_DIR
    } else {
        $userRoot = [Environment]::GetFolderPath("UserProfile")
        if ([string]::IsNullOrWhiteSpace($userRoot)) { throw "Windows user profile directory could not be resolved." }
        Join-Path $userRoot ".config\mise"
    }
    return Join-Path $configRoot "conf.d\winenv.toml"
}

function ConvertTo-TomlString {
    param([string]$Value)
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Sync-WinenvMiseConfig {
    param($Definition)
    $path = Get-WinenvMiseConfigPath
    $tools = @(Get-DefaultPackages $Definition | Where-Object owner -eq "mise" | Sort-Object id)
    $lines = @(
        "# Generated by Winenv. Edit profiles, not this file.",
        "[tools]"
    )
    foreach ($package in $tools) {
        $version = if ($package.version) { [string]$package.version } else { "latest" }
        $lines += "$(ConvertTo-TomlString ([string]$package.id)) = $(ConvertTo-TomlString $version)"
    }
    Write-Plan "Sync Winenv's mise declarations to $path"
    if ($DryRun) { return }
    New-Item -ItemType Directory -Path (Split-Path -Parent $path) -Force | Out-Null
    Set-Content -Path $path -Value ($lines -join "`r`n") -Encoding UTF8
}

function Invoke-MiseProviderInstall {
    param($Package, $Context)
    $profileManaged = $null -ne $Context -and [bool]$Context.ProfileManagedMise
    Install-MisePackage $Package -ProfileManaged:$profileManaged
}

function Invoke-MiseProviderRemove {
    param($Package, $Context)
    $managerCommand = Get-OptionalManagerCommand "mise"
    if ($null -eq $managerCommand) { throw "mise is unavailable." }
    Invoke-Native $managerCommand @("unuse", "--global", [string]$Package.id)
}
